[package]
name = "steam-clip-exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
console   = "0.15.8"
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
indicatif = "0.17.8"
prost     = "0.13.3"
